name: Fetch Images and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy hàng ngày vào lúc 00:00 UTC
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Fetch images
      run: npm run fetch
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
      
    - name: Build
      run: npm run build
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: main
        folder: docs
